# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d832d24b7ca3b77b80dcc9f6c954c6d34fcf04be7140e5db29eb44d8210ff57e969ce4b67b5a9fc3d018d1cae613a242136d4b0d94adc017f0e5e880e8e14f1e

test:
  secret_key_base: 473ca8f429d3185d794d824258145ae922ba47dbd895ead1c8d43ebe71459bee9de52e86df79e26c3756ba7a13505e4ee73f1324745d9164cce6274256545fce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
